### ISSUE TITLE
Task 1 is Open till 8th Oct

### ISSUE THREAD

**Issue by kartikgupta98** [karrocks/Test-Opencode#1]
Check the task 1 folder for instructions

**Comment by Hadeso-0** [comment]
i want to claim

**Comment by Hadeso-0** [comment]
![Untitled-1-01](https://user-images.githubusercontent.com/52004311/135750444-6935fe1a-e130-41b2-b4c4-f95adc06dfc3.jpg)

**Comment by Hadeso-0** [comment]
hi
